name: Node CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install npm dependencies
      run: npm install

    - name: Run build task
      run: npm run build --if-present

    - name: Prepare SSH
    run: >
      cd ~ && mkdir .ssh &&
      touch ~/.ssh/known_hosts &&
      ssh-keyscan -H "$REMOTE_HOST" >>~/.ssh/known_hosts
    env:
      IP: ${{ secrets.REMOTE_HOST  }}

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "./out"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/out/, /node_modules/"